apiVersion: v1
kind: Service
metadata:
  name: fio
  labels:
    app: fio
spec:
  ports:
  - port: 80
    name: fio
  clusterIP: None
  selector:
    app: fio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
spec:
  selector:
    matchLabels:
      app: fio # has to match .spec.template.metadata.labels
  serviceName: "fio"
  replicas: 4 # by default is 1
  template:
    metadata:
      labels:
        app: fio # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: fio
        image: mayadata/fio
        command:
        - /bin/sh
        - -c
        - /tmp/fio-script/fio-loop-iodepth.sh ; sleep 6000
        ports:
        - containerPort: 80
          name: fio
        volumeMounts:
        - name: fio-parm
          mountPath: /etc/fio
        - name: fio-script
          mountPath: /tmp/fio-script
        volumeDevices:
        - devicePath: /dev/sdc
          name: fio-data1
        - devicePath: /dev/sdd
          name: fio-data2
      volumes:
      - name: fio-parm
        configMap:
          name: fio-parm
      - name: fio-script
        configMap:
          name: fio-script
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: fio-data1
    spec:
      volumeMode: Block
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "vsan"
      resources:
        requests:
          storage: 32Gi
  - metadata:
      name: fio-data2
    spec:
      volumeMode: Block
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "vsan"
      resources:
        requests:
          storage: 32Gi
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    fio.parm: |+
      [global]
      ioengine=libaio
      norandommap
      time_based=1
      group_reporting=1
      invalidate=1
      disable_lat=0
      disable_slat=1
      disable_clat=1
      clat_percentiles=0
      direct=1
      invalidate=0
      ramp_time=10
      runtime=30
      iodepth=2
      size=10%
      filename=/dev/sdc:/dev/sdd


      # JOB DEFINITIONS

      [OLTP4K]
      stonewall
      bs=4k
      rw=randrw
      rwmixread=70

      [OLTP16K]
      stonewall
      bs=16k
      rw=randrw
      rwmixread=70

  kind: ConfigMap
  metadata:
    name: fio-parm
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    fio-loop-iodepth.sh: |+
      #!/bin/sh

      # Generate 10 sequence numbers

      for numjobs in `2 2 20`
      do
          # Increase the IO-Depth
        fio /etc/fio/fio.parm --numjobs=$numjobs  --output=/tmp/fio-$numjobs.out
      done

  kind: ConfigMap
  metadata:
    name: fio-script
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
