apiVersion: v1
items:
- apiVersion: v1
  data:
    fio.parm: |+
      [global]
      ioengine=libaio
      norandommap
      time_based=1
      group_reporting=1
      invalidate=1
      disable_lat=0
      disable_slat=1
      disable_clat=1
      clat_percentiles=0
      direct=1
      iodepth=1
      ramp_time=30
      runtime=300
      ################
      #  file section
      ################
      filesize=1g
      directory=/mnt/fio-data
      filename=1:2:3:4:5:6:7:8:9:10:11:12

      # JOB DEFINITIONS

      [OLTP4K]
      stonewall
      bs=4k
      rw=randrw
      rwmixread=70
      numjobs=16

      [OLTP16K]
      stonewall
      bs=16k
      rw=randrw
      rwmixread=70
      numjobs=16

  kind: ConfigMap
  metadata:
    name: fio-parm
    namespace: default
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
