apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-pv
  namespace: mongodb
spec:
  capacity:
    storage: 128Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /container-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ubuntu-k8s-worker-01
