apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongodb
  namespace: mongodb
spec:
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1000Mi
